<h1>Tabla de contenidos 💜<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Fundamentos-prácticos-de-Machine-Learning" data-toc-modified-id="Fundamentos-prácticos-de-Machine-Learning-1">Fundamentos prácticos de Machine Learning</a></span><ul class="toc-item"><li><span><a href="#Fundamentos-prácticos" data-toc-modified-id="Fundamentos-prácticos-1.1">Fundamentos prácticos</a></span><ul class="toc-item"><li><span><a href="#Introducción-a-Numpy" data-toc-modified-id="Introducción-a-Numpy-1.1.1">Introducción a Numpy</a></span></li><li><span><a href="#Introducción-y-manipulación-de-datos-con-Pandas" data-toc-modified-id="Introducción-y-manipulación-de-datos-con-Pandas-1.1.2">Introducción y manipulación de datos con Pandas</a></span></li><li><span><a href="#Introducción-a-SickitLearn" data-toc-modified-id="Introducción-a-SickitLearn-1.1.3">Introducción a SickitLearn</a></span></li><li><span><a href="#Comandos-básicos-de-Numpy" data-toc-modified-id="Comandos-básicos-de-Numpy-1.1.4">Comandos básicos de Numpy</a></span></li><li><span><a href="#Comandos-básicos-de-Pandas" data-toc-modified-id="Comandos-básicos-de-Pandas-1.1.5">Comandos básicos de Pandas</a></span></li><li><span><a href="#Scikit-Learn" data-toc-modified-id="Scikit-Learn-1.1.6">Scikit Learn</a></span></li></ul></li></ul></li></ul></div>

# Fundamentos prácticos de Machine Learning

## Fundamentos prácticos

Recordemos que el Machine Learning se puede definir como la capacidad de un algoritmo de adquirir conocimiento a partir de observaciones, aprender de los datos para mejorar, describir y predecir resultados.

El proceso de implementar algoritmos de Machine Learning se puede ver como:

* Definir el problema
* Construir el modelo y evaluarlo
* Deploy y mejoras

### Introducción a Numpy

Es una biblioteca de Python comúnmente usada en la ciencia de datos. Esta librería trabaja principalmente con arreglos (vectores, matrices y tensores). 

Es muy popular por qué es:

* Sencilla de usar
* Adecuada para el manejo de arreglos
* Rápida

In [2]:
import numpy as np

Para crear arreglos lo hacemos con el metodo `.array` y se administra en forma de listas

In [3]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

podemos llamar a elementos individuales dentro de nuestro array con la notación de índices 

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[4]

5

podemos hacer que nos muestre los datos desde un número hasta el final

In [7]:
a[3 : ]

array([4, 5, 6, 7, 8, 9])

o en un intervalo para que recorra el array hasta encontrar el dato que le pedimos, que en este caso sería el 7

In [10]:
a[3 : 7]

array([4, 5, 6, 7])

podemos imprimir alternando cada n posiciones, en este ejemplo cada 4 "pasos"

In [12]:
a[1 :: 4]

array([2, 6])

también podemos crear arreglos de manera dinámica

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

podemos ingresar las filas y columnas, respecivamente

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

y para saber el tipo de dato de cierto arreglo podemos usar la instrucción `type`

In [28]:
type(np.ones(()))

numpy.ndarray

In [31]:
type(a[1])

numpy.int32

Para generar datos para analizar o crear gráficas podemos usar el comando `linspace` que recibe 3 parámetros, el valor inferior, el valor superior y la cantidad de elementos entre esos 2 valores extremos.

In [32]:
np.linspace(3, 5, 10)

array([3.        , 3.22222222, 3.44444444, 3.66666667, 3.88888889,
       4.11111111, 4.33333333, 4.55555556, 4.77777778, 5.        ])

en el caso donde queremos hacer arreglos de por ejemplo, 2 dimensiones podemos hacerlo con notación de corchetes y separando con comas

In [35]:
b = np.array([ ['x','y','z'],
               ['a','b','c'] ])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'b' 'c']]


numpy.ndarray

para saber cuantas dimensiones tiene nuestro arreglo usamos `.ndim`

In [38]:
b.ndim

2

otro comando que es de muchísima utilidad es `sort` para ordenar el arreglo

In [39]:
c = [12, 4, 10, 40, 2]

In [40]:
np.sort(c)

array([ 2,  4, 10, 12, 40])

podemos usarlo para ordenar estructuras de datos un poco más complejas como las siguientes

In [42]:
cabeceras = [('nombre', 'S10'), ('edad', int)] #S10 representa un string de 10 elementos
datos = [('juan', 10), ('Maria',70), ('Javier', 42), ('Samuel', 15)]

vamos a unir las estructuras anteriores en un array llamado `usuarios`, de forma que integre los 2 valores anteriores en una estructura como la definida en la variable `cabeceras`

In [44]:
usuarios = np.array(datos, dtype = cabeceras)
print(usuarios)

[(b'juan', 10) (b'Maria', 70) (b'Javier', 42) (b'Samuel', 15)]


también podemos ordenarlos igualmente con `sort` y algunos parámetros extra, en este caso tendremos que decirle **el dato que queremos ordenar** y **en base a que elemento lo vamos a ordenar**.

In [45]:
np.sort(usuarios, order = 'edad')

array([(b'juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

también tenemos la opción de llenarlos de una forma dinámica por medio de `.arange`

In [47]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

y agregando un segundo parámetro le definimos nuestros valores inferior y superior, donde el superior es como un intervalo abierto

In [49]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

e indicarle también cada cuanto vamos a incrementar

In [53]:
np.arange(5, 51, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Otra forma de crear arreglos bidimensionales es con la instrucción `np.full()` donde le pasamos como parámetro las dimensiones del arreglo (3x5) y los valores que va a contener

In [54]:
np.full( (3,5) , 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

Finalmente, para trabajar con matrices tenemos la instrucción `diag()` que nos ayuda a crear matrices colocando únicamente los valores de la diagonal y rellenando el resto con 0's

In [56]:
np.diag( [1,3,9,1] )

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 1]])

Ahora como repaso, tratemos de crear un arreglo de 3 dimensiones que podamos ordenar por medio de parámetros como edad, nombre o país.

In [66]:
# Estructura que van a llevar los datos
headers = [('nombre', 'S10'), ('edad', int), ('pais', 'S10')]

In [90]:
# Creamos los datos
data = [('Jesus', 20, 'Mexico'),('Ale', 32, 'Colombia'),('Yes', 25, 'Mexico'),('Luis', 50, 'Honduras'),
         ('Maria', 23, 'Mexico'),('Jhon', 53, 'Canada' ),('Zoom', 13, 'Argentina')]
print(data)

[('Jesus', 20, 'Mexico'), ('Ale', 32, 'Colombia'), ('Yes', 25, 'Mexico'), ('Luis', 50, 'Honduras'), ('Maria', 23, 'Mexico'), ('Jhon', 53, 'Canada'), ('Zoom', 13, 'Argentina')]


In [71]:
# Le damos a datos la estructura de header
users = np.array(data , dtype = headers)

print(users)

[(b'Jesus', 20, b'Mexico') (b'Ale', 32, b'Colombia')
 (b'Yes', 25, b'Mexico') (b'Luis', 50, b'Honduras')
 (b'Maria', 23, b'Mexico') (b'Jhon', 53, b'Canada')
 (b'Zoom', 13, b'Argentina')]


In [72]:
# Ordenamos por edad
np.sort(users , order = 'edad')

array([(b'Zoom', 13, b'Argentina'), (b'Jesus', 20, b'Mexico'),
       (b'Maria', 23, b'Mexico'), (b'Yes', 25, b'Mexico'),
       (b'Ale', 32, b'Colombia'), (b'Luis', 50, b'Honduras'),
       (b'Jhon', 53, b'Canada')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])

In [73]:
# Ordenamos por nombre
np.sort(users, order = 'nombre')

array([(b'Ale', 32, b'Colombia'), (b'Jesus', 20, b'Mexico'),
       (b'Jhon', 53, b'Canada'), (b'Luis', 50, b'Honduras'),
       (b'Maria', 23, b'Mexico'), (b'Yes', 25, b'Mexico'),
       (b'Zoom', 13, b'Argentina')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])

In [74]:
# Ordenamos por país
np.sort(users, order = 'pais')

array([(b'Zoom', 13, b'Argentina'), (b'Jhon', 53, b'Canada'),
       (b'Ale', 32, b'Colombia'), (b'Luis', 50, b'Honduras'),
       (b'Jesus', 20, b'Mexico'), (b'Maria', 23, b'Mexico'),
       (b'Yes', 25, b'Mexico')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])

---

### Introducción y manipulación de datos con Pandas

Pandas es otra librería de Python que es más una extensión de NumPy que se utiliza para manipulación y análisis de datos. En particular ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales.

Al usar Pandas nos vamos a encontrar lo siguiente:

* Manejo de archivos
* Series (1D)
* Dataframes (2D)
* Panels (3D)

In [1]:
import pandas as pd

Vamos a ver la estructura de datos `serie` que es muy parecido a un diccionario o a la forma de una tabla

In [2]:
series = pd.Series( [5, 10, 15, 20, 25] )
print(series)

0     5
1    10
2    15
3    20
4    25
dtype: int64


In [3]:
type(series)

pandas.core.series.Series

también podemos acceder a los elementos individuales

In [4]:
series[3]

20

In [5]:
charac = pd.Series( ['p', 'q', 'r', 's', 't', 'u'] )
print(charac)

0    p
1    q
2    r
3    s
4    t
5    u
dtype: object


La otra estructura con la que vamos a trabajar en Pandas es `dataframe` ya que se usa con regularidad para algoritmos de machine learning y para análisis de datos. Ya que nos acomoda los datos de una forma parecida a como si tuvieramos un  SQL.

In [6]:
lst = ['Holi', 'como', 'tas'] 
df = pd.DataFrame(lst) # Lo convertimos a un DataFrame
print(df)

      0
0  Holi
1  como
2   tas


probemos ahora con una estructura un poco más compleja

In [7]:
data = { 'Nombre': ['Jesus', 'Ana', 'Maria', 'Jose', 'Marco'], 
           'edad': [25, 18, 23, 18, 40],
           'pais': ['Mexico', 'Colobia', 'Brazil', 'Mexico', 'Bolivia']}

df_2 = pd.DataFrame(data)
print(df_2)

  Nombre  edad     pais
0  Jesus    25   Mexico
1    Ana    18  Colobia
2  Maria    23   Brazil
3   Jose    18   Mexico
4  Marco    40  Bolivia


podemos imprimir solo algunas columnas que nos interesen

In [8]:
print(df_2[ [ 'Nombre', 'pais'  ] ])

  Nombre     pais
0  Jesus   Mexico
1    Ana  Colobia
2  Maria   Brazil
3   Jose   Mexico
4  Marco  Bolivia


Vamos a mandar a llamar un archivo .CSV

In [19]:
data = pd.read_csv('../Fundamentos_Practicos_de_Machine_Learning/Archivos/canciones-2018.csv')
# Y mostramos los 5 primeros elementos
data.head(5)

id                          name       artists  \
0  6DCZcSspjsKoFjzjrWoCd                    God's Plan         Drake   
1  3ee8Jmje8o58CHK66QrVC                          SAD!  XXXTENTACION   
2  0e7ipj03S05BNilyu5bRz    rockstar (feat. 21 Savage)   Post Malone   
3  3swc6WTsr7rl9DqQKQA55  Psycho (feat. Ty Dolla $ign)   Post Malone   
4  2G7V7zsVDxg1yRsu7Ew9R                In My Feelings         Drake   

   danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.754   0.449  7.0    -9.211   1.0       0.1090        0.0332   
1         0.740   0.613  8.0    -4.880   1.0       0.1450        0.2580   
2         0.587   0.535  5.0    -6.090   0.0       0.0898        0.1170   
3         0.739   0.559  8.0    -8.011   1.0       0.1170        0.5800   
4         0.835   0.626  1.0    -5.833   1.0       0.1250        0.0589   

   instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
0          0.000083     0.552    0.357   77.169     198973.0             4.0  
1          0.003720     0.123    0.473   75.023     166606.0             4.0  
2          0.000066     0.131    0.140  159.847     218147.0             4.0  
3          0.000000     0.112    0.439  140.124     221440.0             4.0  
4          0.000060     0.396    0.350   91.030     217925.0             4.0

**NOTA:** Al cargar archivos usando `pd.read_csv` podemos ajustar ciertos parámetros para que nos muestre los datos de cierta forma:

* `delimiter` : Funciona como separados de los datos en el CSV
* `decimal` : Notación decimal de los datos.
* `encoding` : Para cambiar el tipo de codificación, por ejemplo de UTF-8 a Latin1

vamos a trabajar con esos datos, por ejemplo agrupemos por nombre de artista

In [22]:
artist = data.artists # Toma "artists" de la columna que ya tiene definida}
artist[5]

'Post Malone'

Ahora queremos buscar información sobre los tipos de datos con los que estamos trabajando, eso lo hacemos con la instrucción `iloc`. Este comando se usa si vamos a usar el indice de las filas y columnas para filtrar nuestros datos. 

In [24]:
info = data.iloc[15]
info

id                     3GCdLUSnKSMJhs4Tj6CV3
name                All The Stars (with SZA)
artists                       Kendrick Lamar
danceability                           0.698
energy                                 0.633
key                                        8
loudness                              -4.946
mode                                       1
speechiness                           0.0597
acousticness                          0.0605
instrumentalness                    0.000194
liveness                              0.0926
valence                                0.552
tempo                                 96.924
duration_ms                           232187
time_signature                             4
Name: 15, dtype: object

también le podemos hacer un `data.tail()` para ver lo que está hasta el final de nuestro archivo (en este caso los últimos 5)

In [30]:
data.tail()

id                               name       artists  \
95  630sXRhIcfwr2e4RdNtjK                  Rewrite The Stars     Zac Efron   
96  2xmrfQpmS2iJExTlklLoA  I Miss You (feat. Julia Michaels)  Clean Bandit   
97  5WvAo7DNuPRmk4APhdPzi                         No Brainer     DJ Khaled   
98  1j4kHkkpqZRBwE0A4CN4Y        Dusk Till Dawn - Radio Edit          ZAYN   
99  3EPXxR3ImUwfayaurPi3c                         Be Alright    Dean Lewis   

    danceability  energy   key  loudness  mode  speechiness  acousticness  \
95         0.684   0.619  10.0    -7.005   1.0       0.0386        0.0716   
96         0.638   0.658   3.0    -6.318   1.0       0.0456        0.2450   
97         0.552   0.760   0.0    -4.706   1.0       0.3420        0.0733   
98         0.258   0.437  11.0    -6.593   0.0       0.0390        0.1010   
99         0.553   0.586  11.0    -6.319   1.0       0.0362        0.6970   

    instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
95          0.000000    0.1220   0.2840  125.046     217440.0             4.0  
96          0.000004    0.0919   0.3300  105.076     205748.0             4.0  
97          0.000000    0.0865   0.6390  135.702     260000.0             5.0  
98          0.000001    0.1060   0.0967  180.043     239000.0             4.0  
99          0.000000    0.0813   0.4430  126.684     196373.0             4.0

Y si queremos saber la forma del archivo podemos usar `data.shape` que nos da las filas y columnas

In [32]:
data.shape

(100, 16)

también podemos obtener las columnas con el método `columns`

In [33]:
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

por ejemplo, si queremos describir alguna de las columnas en particular podemos usar el método `describe()`

In [34]:
data['tempo'].describe()

count    100.000000
mean     119.904180
std       28.795984
min       64.934000
25%       95.730750
50%      120.116000
75%      140.022750
max      198.075000
Name: tempo, dtype: float64

Y también podemos ordenarlo con `.sort_index`, donde le indicamos la posición desde la que queremos ordenar y en que orden.

In [38]:
data.sort_index(axis = 0, ascending = False) #De forma descendente hasta 0

id                               name       artists  \
99  3EPXxR3ImUwfayaurPi3c                         Be Alright    Dean Lewis   
98  1j4kHkkpqZRBwE0A4CN4Y        Dusk Till Dawn - Radio Edit          ZAYN   
97  5WvAo7DNuPRmk4APhdPzi                         No Brainer     DJ Khaled   
96  2xmrfQpmS2iJExTlklLoA  I Miss You (feat. Julia Michaels)  Clean Bandit   
95  630sXRhIcfwr2e4RdNtjK                  Rewrite The Stars     Zac Efron   
..                    ...                                ...           ...   
4   2G7V7zsVDxg1yRsu7Ew9R                     In My Feelings         Drake   
3   3swc6WTsr7rl9DqQKQA55       Psycho (feat. Ty Dolla $ign)   Post Malone   
2   0e7ipj03S05BNilyu5bRz         rockstar (feat. 21 Savage)   Post Malone   
1   3ee8Jmje8o58CHK66QrVC                               SAD!  XXXTENTACION   
0   6DCZcSspjsKoFjzjrWoCd                         God's Plan         Drake   

    danceability  energy   key  loudness  mode  speechiness  acousticness  \
99         0.553   0.586  11.0    -6.319   1.0       0.0362        0.6970   
98         0.258   0.437  11.0    -6.593   0.0       0.0390        0.1010   
97         0.552   0.760   0.0    -4.706   1.0       0.3420        0.0733   
96         0.638   0.658   3.0    -6.318   1.0       0.0456        0.2450   
95         0.684   0.619  10.0    -7.005   1.0       0.0386        0.0716   
..           ...     ...   ...       ...   ...          ...           ...   
4          0.835   0.626   1.0    -5.833   1.0       0.1250        0.0589   
3          0.739   0.559   8.0    -8.011   1.0       0.1170        0.5800   
2          0.587   0.535   5.0    -6.090   0.0       0.0898        0.1170   
1          0.740   0.613   8.0    -4.880   1.0       0.1450        0.2580   
0          0.754   0.449   7.0    -9.211   1.0       0.1090        0.0332   

    instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
99          0.000000    0.0813   0.4430  126.684     196373.0             4.0  
98          0.000001    0.1060   0.0967  180.043     239000.0             4.0  
97          0.000000    0.0865   0.6390  135.702     260000.0             5.0  
96          0.000004    0.0919   0.3300  105.076     205748.0             4.0  
95          0.000000    0.1220   0.2840  125.046     217440.0             4.0  
..               ...       ...      ...      ...          ...             ...  
4           0.000060    0.3960   0.3500   91.030     217925.0             4.0  
3           0.000000    0.1120   0.4390  140.124     221440.0             4.0  
2           0.000066    0.1310   0.1400  159.847     218147.0             4.0  
1           0.003720    0.1230   0.4730   75.023     166606.0             4.0  
0           0.000083    0.5520   0.3570   77.169     198973.0             4.0  

[100 rows x 16 columns]

como practica seleccionemos 3 columnas y vamos a ordenarlas de forma descendente o ascendente:

In [42]:
# Ubicamos las 3 columnas de interes
columns = data[['name', 'artists', 'duration_ms']]

para realizar esto podemos recurrir al método `sort_values()` ya que nos permite ordenar con base en los valores de la columna, en este caso el nombre asignado.

Ordenemos por la duración, de la más larga a la más corta

In [51]:
# Como estamos usando un valor en lugar del indice usamos .s
columns.sort_values(by = 'duration_ms', ascending = False)

name       artists  duration_ms
21                     Te Bot? - Remix    Nio Garcia     417920.0
42                          SICKO MODE  Travis Scott     312820.0
73                     Walk It Talk It         Migos     276147.0
74               Him & I (with Halsey)        G-Eazy     268867.0
29                             Perfect    Ed Sheeran     263400.0
..                                 ...           ...          ...
18                           Moonlight  XXXTENTACION     135090.0
22                                Mine         Bazzi     131064.0
38                             changes  XXXTENTACION     121887.0
28                      Jocelyn Flores  XXXTENTACION     119133.0
94  Everybody Dies In Their Nightmares  XXXTENTACION      95467.0

[100 rows x 3 columns]

ahora de la más corta a la más larga

In [54]:
columns.sort_values(by = 'duration_ms' , ascending = True)

name       artists  duration_ms
94  Everybody Dies In Their Nightmares  XXXTENTACION      95467.0
28                      Jocelyn Flores  XXXTENTACION     119133.0
38                             changes  XXXTENTACION     121887.0
22                                Mine         Bazzi     131064.0
18                           Moonlight  XXXTENTACION     135090.0
..                                 ...           ...          ...
29                             Perfect    Ed Sheeran     263400.0
74               Him & I (with Halsey)        G-Eazy     268867.0
73                     Walk It Talk It         Migos     276147.0
42                          SICKO MODE  Travis Scott     312820.0
21                     Te Bot? - Remix    Nio Garcia     417920.0

[100 rows x 3 columns]

ahora probemos por el nombre de la canción

In [57]:
columns.sort_values(by = 'name', ascending = True)

name              artists  \
77        1, 2, 3 (feat. Jason Derulo & De La Ghetto)          Sofia Reyes   
60                                               2002           Anne-Marie   
34                                    ?chame La Culpa           Luis Fonsi   
15                           All The Stars (with SZA)       Kendrick Lamar   
47  Back To You - From 13 Reasons Why ? Season 2 S...         Selena Gomez   
..                                                ...                  ...   
23                                         Youngblood  5 Seconds of Summer   
38                                            changes         XXXTENTACION   
80                               lovely (with Khalid)        Billie Eilish   
16                               no tears left to cry        Ariana Grande   
2                          rockstar (feat. 21 Savage)          Post Malone   

    duration_ms  
77     201526.0  
60     186987.0  
34     173720.0  
15     232187.0  
47     207905.0  
..          ...  
23     203418.0  
38     121887.0  
80     200186.0  
16     205920.0  
2      218147.0  

[100 rows x 3 columns]

---

### Introducción a SickitLearn

Esta es una biblioteca de Python de código abierto para aprendizaje automático, incluye algoritmos como árboles de decisión, regresión, máquina de soporte vectorial, entre otros.

Esta biblioteca cuenta con:

* Variedad de módulos
* Versatilidad
* Facilidad de uso

Por ejemplo, al querer importar un modelo de aprendizaje solo tenemos que usar la siguiente sintaxis:

```Python
from sklearn
import [modelo]
```

por ejemplo

```Python
# Para hacer pre-procesamiento de datos
from sklearn import preprocessing
# Para establecer nuestros conjuntos de entrenamiento y evaluación
from sklearn import train_test_split 
# Para usar las métricas necesarias para analizar la ejecución de nuestros modelos
from sklearn import metrics 
# Para crear árboles de decisión
from sklearn import tree
```

no ahondaremos más en esta introducción ya que será la librería que más utilizaremos en el transcurso del notebook.

---

### Comandos básicos de Numpy

Importar biblioteca:

In [16]:
import numpy as np

Crear un arreglo unidimensional

In [64]:
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

Crear un arreglo bidimensional:

In [73]:
my_array_2 = np.array([
    ['x','y','z'],
    ['a','b','c']
])
my_array_2

array([['x', 'y', 'z'],
       ['a', 'b', 'c']], dtype='<U1')

Mostrar el número de elementos del arreglo:

In [71]:
len(my_array)

5

In [72]:
len(my_array_2)

2

Sumar todos los elementos de un arreglo unidimensional

In [74]:
np.sum(my_array)

15

Obtener el número máximo de los elementos del arreglo unidimensional:

In [77]:
np.max(my_array)

5

Crear un arreglo de una dimensión lleno de 0's:

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

Crear un arreglo de una dimensión lleno de 1's:

In [80]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Para reconocer el tipo de dato:

In [81]:
type(my_array_2)

numpy.ndarray

Para ordenar un arreglo:

In [88]:
my_array_3 = [10, 9, 1, 4, 6, 7, 0]
np.sort(my_array_3)

array([ 0,  1,  4,  6,  7,  9, 10])

Ordenar un arreglo por su llave:

In [91]:
# Arreglo
headers = [('nombre', 'S10'), ('edad', int), ('pais', 'S10')]
data = [('Jesus', 20, 'Mexico'),('Ale', 32, 'Colombia'),('Yes', 25, 'Mexico'),('Luis', 50, 'Honduras'),
         ('Maria', 23, 'Mexico'),('Jhon', 53, 'Canada' ),('Zoom', 13, 'Argentina')]
users = np.array(data , dtype = headers)

print(users)

[(b'Jesus', 20, b'Mexico') (b'Ale', 32, b'Colombia')
 (b'Yes', 25, b'Mexico') (b'Luis', 50, b'Honduras')
 (b'Maria', 23, b'Mexico') (b'Jhon', 53, b'Canada')
 (b'Zoom', 13, b'Argentina')]


In [92]:
np.sort(users , order = 'nombre')

array([(b'Ale', 32, b'Colombia'), (b'Jesus', 20, b'Mexico'),
       (b'Jhon', 53, b'Canada'), (b'Luis', 50, b'Honduras'),
       (b'Maria', 23, b'Mexico'), (b'Yes', 25, b'Mexico'),
       (b'Zoom', 13, b'Argentina')],
      dtype=[('nombre', 'S10'), ('edad', '<i4'), ('pais', 'S10')])

Crear un arreglo de 0 a N elementos:

In [95]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Crear un arreglo de N a M elementos:

In [96]:
np.arange(5, 15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Crear un arreglo de N a M elementos cada X valores:

In [97]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

Crear un arreglo de N x M:

In [103]:
np.full( (5,10) , 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### Comandos básicos de Pandas

Importar biblioteca:

In [106]:
import pandas as ps

Generar una serie con Pandas:

In [107]:
pd.Series( [5, 10, 15, 20, 25] )

0     5
1    10
2    15
3    20
4    25
dtype: int64

Crear un DataFrame:

In [109]:
lst = ['Un','data', 'frame']
df = pd.DataFrame(lst)
print(df)

       0
0     Un
1   data
2  frame


Crear un DataFrame con llave y dato:

In [112]:
data = {'Nombre': ['Abd', 'Osc', 'Dav', 'Ros'],
       'Edad': [25, 15, 19, 23],
       'Pais': ['MX', 'CO', 'BR','MX']}

df = pd.DataFrame(data)
print(df)

  Nombre  Edad Pais
0    Abd    25   MX
1    Osc    15   CO
2    Dav    19   BR
3    Ros    23   MX


Leer archivo .CSV:

In [114]:
data = pd.read_csv("../Fundamentos_Practicos_de_Machine_Learning/Archivos/salarios.csv")
print(data)

    Aexperiencia  Salario
0           10.0    42500
1            8.0    36302
2            5.4    35000
3            2.5    18103
4            1.0    15000
5            8.0    37000
6            4.0    26300
7            6.0    35201
8            2.0    18302
9           10.0    42000
10           4.0    27000
11           7.0    35201
12           3.0    19201
13           5.0    28000
14           2.0    17000
15           5.0    33402
16           3.0    19000
17           2.0    18200
18           3.0    19000
19           2.0    17301
20           5.0    28000
21           3.4    20000
22           5.3    27900
23           2.1    17500
24           9.2    40000
25          10.0    42500
26           3.2    18300
27          10.0    40000
28           4.0    25000
29           1.0    15000


Mostrar cabecera:

In [115]:
data.head(3)

Aexperiencia  Salario
0          10.0    42500
1           8.0    36302
2           5.4    35000

Mostrar columna del archivo leído:

In [127]:
data.Salario

0     42500
1     36302
2     35000
3     18103
4     15000
5     37000
6     26300
7     35201
8     18302
9     42000
10    27000
11    35201
12    19201
13    28000
14    17000
15    33402
16    19000
17    18200
18    19000
19    17301
20    28000
21    20000
22    27900
23    17500
24    40000
25    42500
26    18300
27    40000
28    25000
29    15000
Name: Salario, dtype: int64

Mostrar los últimos elementos:

In [121]:
data.tail()

Aexperiencia  Salario
25          10.0    42500
26           3.2    18300
27          10.0    40000
28           4.0    25000
29           1.0    15000

Mostrar tamaño del archivo leído:

In [123]:
data.shape

(30, 2)

Mostrar columnas:

In [128]:
data.columns

Index(['Aexperiencia', 'Salario'], dtype='object')

Describir una columna:

In [129]:
data['Aexperiencia'].describe()

count    30.000000
mean      4.870000
std       2.899721
min       1.000000
25%       2.625000
50%       4.000000
75%       6.750000
max      10.000000
Name: Aexperiencia, dtype: float64

Ordenar datos del archivo leído:

In [130]:
data.sort_index(axis = 0 , ascending = False)

Aexperiencia  Salario
29           1.0    15000
28           4.0    25000
27          10.0    40000
26           3.2    18300
25          10.0    42500
24           9.2    40000
23           2.1    17500
22           5.3    27900
21           3.4    20000
20           5.0    28000
19           2.0    17301
18           3.0    19000
17           2.0    18200
16           3.0    19000
15           5.0    33402
14           2.0    17000
13           5.0    28000
12           3.0    19201
11           7.0    35201
10           4.0    27000
9           10.0    42000
8            2.0    18302
7            6.0    35201
6            4.0    26300
5            8.0    37000
4            1.0    15000
3            2.5    18103
2            5.4    35000
1            8.0    36302
0           10.0    42500

---

### Scikit Learn

Importar biblioteca:

```Python
from sklearn import [modulo] ```

In [11]:
from sklearn import tree
from sklearn.model_selection import train_test_split

División del conjunto de datos para entrenamiento y para pruebas:

In [19]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

Entrenar modelo:

``` Python
[modelo].fit(X_train, y_train)
```

In [23]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()
from sklearn import svm
clf = svm.SVC(gamma=0.001, C=100.)

In [24]:
clf.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100.0, gamma=0.001)

Predicción del modelo:

```Python
Y_pred = [modelo].predict(X_test)
```

Matriz de confusión:

```Python
Y_pred = [modelo].predict(X_test)```

In [25]:
from sklearn.metrics import confusion_matrix
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]

confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]], dtype=int64)

Calcular la exactitud:

``` Python
metrics.accuracy_score(y_test, y_pred)
```

In [26]:
from sklearn.metrics import accuracy_score
y_pred = [0, 2, 1, 3]
y_true = [0, 1, 2, 3]
accuracy_score(y_true, y_pred)

0.5

---